// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbau01aJqBWonKujqWZTFOAg9VUUJcXg0',
    appId: '1:176203389940:web:bf961f80d22b74816737a1',
    messagingSenderId: '176203389940',
    projectId: 'chatzoo-app',
    authDomain: 'chatzoo-app.firebaseapp.com',
    storageBucket: 'chatzoo-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDmQrucbIX7vWFGUgDA6qqc79viiTeJVs',
    appId: '1:176203389940:android:e33f2f631e33895c6737a1',
    messagingSenderId: '176203389940',
    projectId: 'chatzoo-app',
    storageBucket: 'chatzoo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBadQc-leiXY0mu4iGo5toe8acR8CG0OP8',
    appId: '1:176203389940:ios:2a963916616359666737a1',
    messagingSenderId: '176203389940',
    projectId: 'chatzoo-app',
    storageBucket: 'chatzoo-app.firebasestorage.app',
    iosBundleId: 'com.example.chatzooApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBadQc-leiXY0mu4iGo5toe8acR8CG0OP8',
    appId: '1:176203389940:ios:2a963916616359666737a1',
    messagingSenderId: '176203389940',
    projectId: 'chatzoo-app',
    storageBucket: 'chatzoo-app.firebasestorage.app',
    iosBundleId: 'com.example.chatzooApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbau01aJqBWonKujqWZTFOAg9VUUJcXg0',
    appId: '1:176203389940:web:8c7328889d58c95f6737a1',
    messagingSenderId: '176203389940',
    projectId: 'chatzoo-app',
    authDomain: 'chatzoo-app.firebaseapp.com',
    storageBucket: 'chatzoo-app.firebasestorage.app',
  );

}